jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    firewalls:
        # aquí configuras las partes de la aplicación que se protegen
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        administracion:
            pattern:        ^/admin
            #provider:       admin
            anonymous:      ~
            form_login:
                login_path: /admin/login
                check_path: /admin/login_check
            logout:
                path:       /admin/logout
                target:     /admin

        privado:
            pattern:        ^/privado
            #provider:       user
            anonymous:      ~
            form_login:
                login_path: /privado/login
                check_path: /privado/login_check
            logout:
                path:       /privado/logout
                target:     /privado

        publico:
            pattern:        ^/*
            anonymous:      ~

    access_control:
        # aquí configuras qué usuarios pueden acceder a cada parte del sitio
        - { path: ^/privado/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/privado/*,     roles: ROLE_USER }
        - { path: ^/admin/login,   roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/*,       roles: ROLE_ADMIN }

    providers:
        # in_memory:
        #     memory:
        #         users:
        #             user:  { password: userpass, roles: [ 'ROLE_USER' ] }
        #             admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

        # aquí configuras de dónde salen los usuarios de la aplicación
        users:
            entity: { class: Asignaciones\UsuarioBundle\Entity\Usuario, property: username }


    encoders:
        # aquí configuras cómo se codifican las contraseñas de cada usuario
        Asignaciones\UsuarioBundle\Entity\Usuario:  { algorithm: sha512, iterations: 10 }


    role_hierarchy:
         ROLE_ADMIN:       ROLE_USER
         ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]